version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "America/Chicago"
    open-pull-requests-limit: 3
    versioning-strategy: "increase-if-necessary"
    groups:
      production-minor-patch:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
      development-minor-patch:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
      security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "America/Chicago"
    open-pull-requests-limit: 3
    versioning-strategy: "increase-if-necessary"
    groups:
      python-minor-patch:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
      python-security:
        applies-to: "security-updates"
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "America/Chicago"
    open-pull-requests-limit: 3
    groups:
      github-actions:
        patterns:
          - "*"
      github-actions-security:
        applies-to: "security-updates"
        patterns:
          - "*"
